DOMAIN-SUFFIX,push.apple.com,Proxies
DOMAIN-SUFFIX,sandbox.push.apple.com,Proxies
DOMAIN-SUFFIX,api.push.apple.com,Proxies
DOMAIN-SUFFIX,gateway.push.apple.com,Proxies

IP-CIDR,17.249.0.0/16,Proxies,no-resolve
IP-CIDR,17.252.0.0/16,Proxies,no-resolve
IP-CIDR,17.57.144.0/22,Proxies,no-resolve
IP-CIDR,17.188.128.0/18,Proxies,no-resolve
IP-CIDR,17.188.20.0/23,Proxies,no-resolve
IP-CIDR6,2620:149:a44::/48,Proxies,no-resolve
IP-CIDR6,2403:300:a42::/48,Proxies,no-resolve
IP-CIDR6,2403:300:a51::/48,Proxies,no-resolve
IP-CIDR6,2a01:b740:a42::/48,Proxies,no-resolve